name: kinfraglib
channels:
  - conda-forge
dependencies:
  # Base dependencies
  - python
  - pip
  # Package dependencies
  - biopandas
  - chembl_webresource_client
  - ijson
  - ipywidgets>=7.5
  - jupyterlab
  - matplotlib
  - numpy
  - pandas=2.0    
  - rdkit=2023.03
  - scikit-learn
  - seaborn
  - opencadd
  ## CI tests
  # Workaround for https://github.com/computationalmodelling/nbval/issues/153 -> SOLVED? TODO
  - pytest # 5.*
  - pytest-xdist
  - nbval
  - shyaml
  - pip:
    - black-nb
    # KinFragLib itself
    - https://github.com/volkamerlab/kinfraglib/archive/master.tar.gz
